name: Docker Image CI

on: workflow_dispatch
  # push:
  #   branches: [ "uat" ]
  # pull_request:
  #   branches: [ "uat" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login (Yandex Cloud)
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.iac_sacc_secret }}

    - name: Build image (Yandex Cloud)
      env:
        CR_REGISTRY: crp520okjbk610p5su7h
        CR_REPOSITORY: iac
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user$IMAGE_TAG ./finnhubProducer/
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:user$IMAGE_TAG
