name: Docker Image CI

on: workflow_dispatch
  # push:
  #   branches: [ "uat" ]
  # pull_request:
  #   branches: [ "uat" ]
  
jobs:
  docker:
    name: 'Docker build/push'
    runs-on: ubuntu-latest
    environment: uat

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # - name: Login (Yandex Cloud)
    #   id: login-cr
    #   uses: yc-actions/yc-cr-login@v1
    #   with:
    #     yc-sa-json-credentials: ${{ secrets.iac_sacc_secret }}
    - name: IAM Token
      id: issue-iam-token
      uses: yc-actions/yc-iam-token@v1
      with: 
        yc-key-id: ${{ secrets.YC_KEY_ID }}
        yc-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
        yc-private-key: ${{ secrets.YC_PRIVATE_KEY }}

    - name: Build image (Yandex Cloud)
      env:
        CR_REGISTRY: crp520okjbk610p5su7h
        CR_REPOSITORY: finnhub_producer
        WORK_DIR: finnhubProducer
        IMAGE_TAG: ${{ github.sha }}
        YC_TOKEN: ${{ steps.issue-iam-token.outputs.token }}
      run: |
        docker login --username iam --password $YC_TOKEN cr.yandex
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest ./$WORK_DIR/
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
