name: 'main'

on: workflow_dispatch


permissions:
  contents: read

jobs:
  main:
    name: 'Terraform test'
    runs-on: ubuntu-latest
    environment: uat
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2    
    - name: 'LL'
      run: 'tree'
    - name: 'build and push docker images'
      uses: ./.github/workflows/docker-image.yml@main
      with:
        version: 0.1.0
        environment: uat
    - name: 'Applay uat'
      uses: ./.github/workflows/terraform_apply.yml
      with:
        version: 0.1.0
        environment: uat

    - name: 'Testing'
      uses: ./.github/workflows/test.yml
      with:
        version: 0.1.0
        environment: uat
    - name: 'Destroy uat'
      if: always()
      uses: ./.github/workflows/terraform_destroy.yml
      with:
        version: 0.1.0
        environment: uat
    - name: 'build and push docker images'
      uses: ./.github/workflows/docker-image.yml
      with:
        version: 0.1.0
        environment: prod
    
    - name: 'Applay prod'
      uses: ./.github/workflows/terraform_apply.yml
      with:
        version: 0.1.0
        environment: prod
    # create and apply PR from uat to prod