name: 'main'

on: workflow_dispatch

jobs:
  main:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: uat
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
  call-test:
    uses: Tousep/stream_finnhub_YC/.github/workflows/test.yml@main
    with:
      environmentсс: uatuat