name: 'Test infra'

on:
  workflow_call:
    inputs: 
      version:
        description: 'Version'
        required: True
        type: string
      environment:
        description: Environment
        required: True  
        type: string
  workflow_dispatch:
    inputs: 
      version:
        description: 'Version'
        required: True
        type: string
      environment:
        description: 'Environment'
        required: True
        type: choice
        options:
        - uat
        - prod
 
permissions:
  contents: read

jobs:
  test_infra:
    name: 'Test infra'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set 8.8.8.8 as dns server
        run: |
          sudo sed -i 's/#DNS=/DNS=8.8.8.8 8.8.4.4/g' /etc/systemd/resolved.conf
          sudo systemctl daemon-reload
          sudo systemctl restart systemd-networkd
          sudo systemctl restart systemd-resolved
      - run: |
            sudo prlimit --pid $$ --nofile=500000:500000
            ulimit -a
      - run: mkdir --parents ./ca-certificates/Yandex
      - uses: wei/wget@v1
        with:
          args: -O ./ca-certificates/Yandex/RootCA.crt https://storage.yandexcloud.net/cloud-certs/RootCA.pem
      - uses: wei/wget@v1
        with:
          args: -O ./ca-certificates/Yandex/IntermediateCA.crt https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem
      - uses: wei/wget@v1
        with:
          args: -O ./ca-certificates/Yandex/YandexInternalRootCA.crt https://storage.yandexcloud.net/cloud-certs/CA.pem
      # - name: chmod
      #   run: chmod 655 ./ca-certificates/Yandex/RootCA.crt
      #     chmod 655 ./ca-certificates/Yandex/IntermediateCA.crt
      # - name: update serts
      #   run: update-ca-certificates
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r ./terraform-ydb/test/requirements.txt
      - name: pytest kafka
        env: 
          uniq_msg: ${{ github.sha }}
        run: python ./terraform-ydb/test/kafka.py
      - name: pytest clichouse
        env: 
          uniq_msg: ${{ github.sha }}
        run: python ./terraform-ydb/test/clickhouse.py