name: 'Test infra'

on:
  workflow_call:
    inputs: 
      version:
        description: 'Version'
        required: True
        type: string
      environment:
        description: Environment
        required: True  
        type: string
  workflow_dispatch:
    inputs: 
      version:
        description: 'Version'
        required: True
        type: string
      environment:
        description: 'Environment'
        required: True
        type: choice
        options:
        - uat
        - prod
 
permissions:
  contents: read

jobs:
  test_infra:
    name: 'Test infra'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
      - name: add sert
        run: mkdir --parents ./ca-certificates/Yandex && \
          wget "https://storage.yandexcloud.net/cloud-certs/RootCA.pem" \
            --output-document ./ca-certificates/Yandex/RootCA.crt && \
          wget "https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem" \
            --output-document ./ca-certificates/Yandex/IntermediateCA.crt && \
          chmod 655 \
            ./ca-certificates/Yandex/RootCA.crt \
            ./ca-certificates/Yandex/IntermediateCA.crt && \
          update-ca-certificates